set -g status-bg black
set -g status-fg white
set -g status-style default
set-window-option -g mode-keys vi
set-window-option -g history-limit 50000
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

set -g pane-active-border-style fg=default,bg=default

# Enable repeat for Option-arrow key resizing (Ctrl-b prefix)
bind -r M-Up resize-pane -U 5
bind -r M-Down resize-pane -D 5
bind -r M-Left resize-pane -L 5
bind -r M-Right resize-pane -R 5

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "arcticicestudio/nord-tmux"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @resurrect-strategy-nvim 'session'

# Local config files
source-file ~/.config/tmux/plugins/nordfox.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Tie ssh permission unlock to login session, not tmux session
set-option -g update-environment "SSH_AUTH_SOCK SSH_AGENT_PID"
